FROM node:18-alpine

WORKDIR /app


RUN apk add --no-cache openssl


COPY package*.json ./
COPY prisma/schema.prisma ./prisma/


RUN npm install --ignore-scripts
RUN npx prisma generate


COPY . .

RUN npx prisma generate

EXPOSE 3000

COPY migrate.sh /app/migrate.sh
RUN chmod +x /app/migrate.sh
ENTRYPOINT ["/app/migrate.sh"]

# Run in dev mode with hot-reload
CMD ["npm", "run", "dev", "--", "--hostname", "0.0.0.0"]